services:
  peerflow-ui-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:3000"
    volumes:
      # Preserves the "node_modules" directory of the container
      # without this anonymous volume, the local "node_modules" directory
      # would overwrite the container's "node_modules" directory
      - /app/node_modules
      - ./src:/app
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      
