apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- auth-profiling-service-deployment.yaml
- mongodb-auth-deployment.yaml
- assignment-service-deployment.yaml
- mongodb-assignment-deployment.yaml
- assignment-submission-service-deployment.yaml
- mongodb-assignment-submission-deployment.yaml
- review-assignment-service-deployment.yaml
- mongodb-review-assignment-deployment.yaml
- processing-service-deployment.yaml
- mongodb-processing-deployment.yaml
- seaweedfs-deployment.yaml
- orchestrator-service-deployment.yaml