apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: peerflow-app-prod
resources:
- ../../base
- namespace.yaml

# Image patches
patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: auth-profiling-service
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: giosuciaravola/peerflow-auth-profiling-service:prod

- target:
    group: apps
    version: v1
    kind: Deployment
    name: assignment-service
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: giosuciaravola/peerflow-assignment-service:prod

- target:
    group: apps
    version: v1
    kind: Deployment
    name: assignment-submission-service
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: giosuciaravola/peerflow-assignment-submission-service:prod

- target:
    group: apps
    version: v1
    kind: Deployment
    name: review-assignment-service
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: giosuciaravola/peerflow-review-assignment-service:prod

- target:
    group: apps
    version: v1
    kind: Deployment
    name: processing-service
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: giosuciaravola/peerflow-processing-service:prod

- target:
    group: apps
    version: v1
    kind: Deployment
    name: orchestrator-service
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: giosuciaravola/peerflow-orchestrator-service:prod

- target:
    group: apps
    version: v1
    kind: Deployment
    name: peerflow-ui-service
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: giosuciaravola/peerflow-ui-service:prod

# Service patches - making services accessible externally
- target:
    version: v1
    kind: Service
    name: auth-profiling-service
  patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30010

- target:
    version: v1
    kind: Service
    name: assignment-service
  patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30020

- target:
    version: v1
    kind: Service
    name: assignment-submission-service
  patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30030

- target:
    version: v1
    kind: Service
    name: seaweedfs-filer
  patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30031

- target:
    version: v1
    kind: Service
    name: review-assignment-service
  patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30040

- target:
    version: v1
    kind: Service
    name: processing-service
  patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30050

- target:
    version: v1
    kind: Service
    name: orchestrator-service
  patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30060

- target:
    version: v1
    kind: Service
    name: peerflow-ui-service
  patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30070