FROM python:3.11-alpine

WORKDIR /app

# Install dependencies
COPY ./requirements.txt .
RUN pip install --no-cache-dir --upgrade -r requirements.txt
RUN pip uninstall -y jwt pyjwt
RUN pip install --no-cache-dir pyjwt


# Don't copy the code - it will be mounted as a volume instead
# The src directory will be mounted from the host

# Run the application with reload enabled
CMD ["fastapi", "dev", "/app/src/app.py", "--port", "3000", "--host", "0.0.0.0"]